#define SEVENSEGMENTLED1 13//
#define SEVENSEGMENTLED2 14//
#define SEVENSEGMENTLED3 12//
#define SEVENSEGMENTLED4 15//
#define SEVENSEGMENTLED5 16//
#define SEVENSEGMENTLED6 18//
#define SEVENSEGMENTLED7 17//



void setup() {
 pinMode(SEVENSEGMENTLED1,OUTPUT);
 
 pinMode(SEVENSEGMENTLED2,OUTPUT);
 
 pinMode(SEVENSEGMENTLED3,OUTPUT);
 
 pinMode(SEVENSEGMENTLED4,OUTPUT);
 
 pinMode(SEVENSEGMENTLED5,OUTPUT);
 
 pinMode(SEVENSEGMENTLED6,OUTPUT);
 
 pinMode(SEVENSEGMENTLED7,OUTPUT);

  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

digitalWrite(SEVENSEGMENTLED1,HIGH);
digitalWrite(SEVENSEGMENTLED2,HIGH);
digitalWrite(SEVENSEGMENTLED3,HIGH);
digitalWrite(SEVENSEGMENTLED4,HIGH);
digitalWrite(SEVENSEGMENTLED5,HIGH);
digitalWrite(SEVENSEGMENTLED6,HIGH);
digitalWrite(SEVENSEGMENTLED7,LOW);
delay(1000);
digitalWrite(SEVENSEGMENTLED1,HIGH);
digitalWrite(SEVENSEGMENTLED2,HIGH);
digitalWrite(SEVENSEGMENTLED3,HIGH);
digitalWrite(SEVENSEGMENTLED4,HIGH);
digitalWrite(SEVENSEGMENTLED5,HIGH);
digitalWrite(SEVENSEGMENTLED6,LOW);
digitalWrite(SEVENSEGMENTLED7,LOW);
delay(1000);
digitalWrite(SEVENSEGMENTLED1,HIGH);
digitalWrite(SEVENSEGMENTLED2,HIGH);
digitalWrite(SEVENSEGMENTLED3,HIGH);
digitalWrite(SEVENSEGMENTLED4,HIGH);
digitalWrite(SEVENSEGMENTLED5,HIGH);
digitalWrite(SEVENSEGMENTLED6,LOW);
digitalWrite(SEVENSEGMENTLED7,LOW);
delay(1000);
digitalWrite(SEVENSEGMENTLED1,LOW);
digitalWrite(SEVENSEGMENTLED2,HIGH);
digitalWrite(SEVENSEGMENTLED3,LOW);
digitalWrite(SEVENSEGMENTLED4,LOW);
digitalWrite(SEVENSEGMENTLED5,HIGH);
digitalWrite(SEVENSEGMENTLED6,LOW);
digitalWrite(SEVENSEGMENTLED7,HIGH);
delay(1000);
digitalWrite(SEVENSEGMENTLED1,HIGH);
digitalWrite(SEVENSEGMENTLED2,HIGH);
digitalWrite(SEVENSEGMENTLED3,LOW);
digitalWrite(SEVENSEGMENTLED4,HIGH);
digitalWrite(SEVENSEGMENTLED5,HIGH);
digitalWrite(SEVENSEGMENTLED6,LOW);
digitalWrite(SEVENSEGMENTLED7,HIGH);
delay(2000);
}
